<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Microsoft.Azure.WebJobs.Shared\WebJobs.Shared.projitems" Label="Shared" />

  <PropertyGroup>
    <Version>3.0.42$(VersionSuffix)</Version>
    <InformationalVersion>$(Version) Commit hash: $(CommitHash)</InformationalVersion>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageId>Microsoft.Azure.WebJobs.Logging.ApplicationInsights</PackageId>
    <Description>This package adds Application Insights based logging capabilities to the WebJobs SDK. For more information, please visit https://go.microsoft.com/fwlink/?linkid=2279708.</Description>
    <AssemblyName>Microsoft.Azure.WebJobs.Logging.ApplicationInsights</AssemblyName>
    <RootNamespace>Microsoft.Azure.WebJobs.Logging.ApplicationInsights</RootNamespace>
    <StyleCopTreatErrorsAsWarnings>false</StyleCopTreatErrorsAsWarnings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <ItemGroup>
    <!--
    Explicitly referencing a package rather than using a project reference to allow us to release this package 
    without all of the others in this solution. If changes to WebJobs.Host are needed here, re-introduce the
    project reference.
    -->
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.39" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.11.4" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.SnapshotCollector" Version="1.4.6" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="2.1.1" />
    <PackageReference Include="System.Diagnostics.TraceSource" Version="4.3.0" />
    <PackageReference Include="System.Threading" Version="4.3.0" />
    <PackageReference Include="System.Threading.Thread" Version="4.3.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta004" PrivateAssets="all" />
  </ItemGroup>

</Project>
