<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <PackageId>Microsoft.Azure.WebJobs.Host.TestCommon</PackageId>
    <Description>This package contains helpers and Types useful for WebJobs SDK testing. For more information, please visit https://go.microsoft.com/fwlink/?linkid=2279708.</Description>
    <AssemblyName>Microsoft.Azure.WebJobs.Host.TestCommon</AssemblyName>
    <RootNamespace>Microsoft.Azure.WebJobs.Host.TestCommon</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.22.1" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.20.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.2.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118" PrivateAssets="all" />
    <PackageReference Include="xunit" Version="2.9.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Microsoft.Azure.WebJobs.Host.Storage\WebJobs.Host.Storage.csproj" />
    <ProjectReference Include="..\..\src\Microsoft.Azure.WebJobs.Host\WebJobs.Host.csproj" />
  </ItemGroup>

</Project>
