language: csharp
sudo: false
dist: trusty
dotnet: 2.0.0
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
addons:
  apt:
    packages:
      - libunwind8
mono: none
os:
  - linux
osx_image: xcode9.1
branches:
  only:
    - master
    - dev
    - v2.x
    - travis
    - /^(.*\/)?ci-.*$/
    - /^rel\/.*/
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
before_script:
  - chmod a+x ./build.sh
script:
  - ./build.sh