language: csharp
sudo: false
dist: trusty
dotnet: 2.0.0
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: none
os:
  - linux
  - osx
osx_image: xcode8.2
branches:
  only:
    - master
    - dev
    - v2.x
    - travis
    - /^(.*\/)?ci-.*$/
    - /^rel\/.*/
before_script:
  - chmod a+x ./build.sh
script:
  - ./build.sh