variables:
- group: 'WebJobs SDK Testing'
- name: buildNumber
  value: $[ counter('constant', 12000) ]
- name: buildOutputDirectory
  value: '$(System.DefaultWorkingDirectory)\buildoutput'
- name: buildVersion
  value: '3.0.$(buildNumber)'
  ## NOTE: This variable denotes the overall build version and is distinct from individual package versions.
- name: isPr
  value: $[ eq(variables['Build.Reason'], 'PullRequest') ]
- name: hasTag
  value: $[ startsWith(variables['Build.SourceBranch'], 'refs/tags') ]
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: ${{ true }}

pr:
  branches:
    include:
    - dev
    - master

trigger:
  branches:
    include:
    - dev
    - master
  tags:
    include:
      - '*'

jobs:
- job: BuildAndTest
  pool:
    name: '1ES-Hosted-AzFunc'
    demands:
    - ImageOverride -equals MMS2019TLS

  steps:
  - template: build/install-dotnet.yml

  - task: 1ESHostedPoolValidation@1

  - task: DotNetCoreCLI@2
    displayName: 'Build source'
    inputs:
      command: 'build'
      arguments: '-c Release'
      projects: 'Webjobs.sln'
    env:
      CommitHash: $(Build.SourceVersion)

  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: 'test'
      arguments: '--no-build -c Release'
      projects: |
        test\Microsoft.Azure.WebJobs.Extensions.Rpc.UnitTests\*.csproj
        test\Microsoft.Azure.WebJobs.Host.UnitTests\*.csproj
        test\Microsoft.Azure.WebJobs.Host.FunctionalTests\*.csproj
        test\Microsoft.Azure.WebJobs.Logging.FunctionalTests\*.csproj
        test\Microsoft.Azure.WebJobs.Host.EndToEndTests\*.csproj
    env:
      AzureWebJobsDashboard: $(Storage)
      AzureWebJobsStorage: $(Storage)
      AzureWebJobsSecondaryStorage: $(Storage2)
      AzureWebJobsServiceBus: $(ServiceBus)
      AzureWebJobsServiceBusSecondary: $(ServiceBus2)
      AzureWebJobsTestHubConnection: $(EventHub)
      AzureWebJobsTestHubConnection2: $(EventHub2)
      APPINSIGHTS_REPORTER_KEY: $(AppInsights)
      ConnectionStrings:ServiceBus: $(ServiceBus)
      ConnectionStrings:ServiceBusSecondary: $(ServiceBus2)

  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@2
    displayName: 'ESRP CodeSigning - Authenticode'
    condition: eq(variables.isPr, false)
    inputs:
      ConnectedServiceName: 'ESRP Service'
      FolderPath: 'src'
      Pattern: Microsoft.Azure.WebJobs.*.dll
      signConfigType: inlineSignParams
      inlineOperation: |
        [
          {
              "KeyCode" : "CP-233863-SN",
              "OperationCode" : "StrongNameSign",
              "Parameters" : {},
              "ToolName" : "sign",
              "ToolVersion" : "1.0"
          },
          {
              "KeyCode" : "CP-233863-SN",
              "OperationCode" : "StrongNameVerify",
              "Parameters" : {},
              "ToolName" : "sign",
              "ToolVersion" : "1.0"
          },
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolSign",
            "Parameters": {
              "OpusName": "Microsoft",
              "OpusInfo": "http://www.microsoft.com",
              "FileDigest": "/fd \"SHA256\"",
              "PageHash": "/NPH",
              "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            "ToolName": "sign",
            "ToolVersion": "1.0"
          },
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolVerify",
            "Parameters": {},
            "ToolName": "sign",
            "ToolVersion": "1.0"
          }
        ]
  
  - task: DotNetCoreCLI@2
    displayName: 'Pack'
    inputs:
      command: 'custom'
      custom: 'pack'
      ${{ if eq(variables.hasTag, true) }}:
        arguments: '--no-build -c Release -o $(buildOutputDirectory)'
      ${{ else }}:
        arguments: '--no-build -c Release -o $(buildOutputDirectory) --version-suffix -$(buildNumber)'
      projects: |
        src\Microsoft.Azure.WebJobs.Host\WebJobs.Host.csproj
        src\Microsoft.Azure.WebJobs.Host\WebJobs.Host.Sources.csproj
        src\Microsoft.Azure.WebJobs.Logging\WebJobs.Logging.csproj
        src\Microsoft.Azure.WebJobs.Logging.ApplicationInsights\WebJobs.Logging.ApplicationInsights.csproj
        src\Microsoft.Azure.WebJobs.Host.Storage\WebJobs.Host.Storage.csproj
        src\Microsoft.Azure.WebJobs.Rpc.Core\WebJobs.Rpc.Core.csproj
        src\Microsoft.Azure.WebJobs.Extensions.Rpc\WebJobs.Extensions.Rpc.csproj
        test\Microsoft.Azure.WebJobs.Host.TestCommon\WebJobs.Host.TestCommon.csproj

  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@2
    displayName: 'ESRP CodeSigning: Nupkg'
    condition: eq(variables.isPr, false)
    inputs:
      ConnectedServiceName: 'ESRP Service'
      FolderPath: '$(buildOutputDirectory)'
      Pattern: 'Microsoft.Azure.WebJobs*.nupkg'
      signConfigType: inlineSignParams
      inlineOperation: |
        [
            {
              "KeyCode": "CP-401405",
              "OperationCode": "NuGetSign",
              "Parameters": {},
              "ToolName": "sign",
              "ToolVersion": "1.0"
            },
            {
              "KeyCode": "CP-401405",
              "OperationCode": "NuGetVerify",
              "Parameters": {},
              "ToolName": "sign",
              "ToolVersion": "1.0"
            }
        ]

  - task: ManifestGeneratorTask@0
    displayName: "SBOM Generation"
    inputs:
      BuildDropPath: '$(buildOutputDirectory)'
      Verbosity: 'Information'

  - publish: '$(buildOutputDirectory)'
    artifact: drop