<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AssemblyName>Microsoft.Azure.WebJobs.Extensions.Rpc.UnitTests</AssemblyName>
    <RootNamespace>Microsoft.Azure.WebJobs.Extensions.Rpc.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.53.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="Moq" Version="4.18.4" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Microsoft.Azure.WebJobs.Extensions.Rpc/Webjobs.Extensions.Rpc.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="protos/test.proto" GrpcServices="Server" />
  </ItemGroup>

</Project>
