<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net8.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <PackageId>Microsoft.Azure.WebJobs.Extensions.Rpc</PackageId>
    <Description>This package provides RPC capabilities to the WebJobs SDK, allowing extensions to communicate between the host and worker via RPC. For more information, please visit https://go.microsoft.com/fwlink/?linkid=2279708.</Description>
    <AssemblyName>Microsoft.Azure.WebJobs.Extensions.Rpc</AssemblyName>
    <RootNamespace>Microsoft.Azure.WebJobs.Extensions.Rpc</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.Azure.WebJobs.Rpc.Core\WebJobs.Rpc.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
  </ItemGroup>

</Project>
