<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))"
          Condition="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../')) != ''" />
          
  <PropertyGroup>
    <ArtifactsPath>$(MSBuildThisFileDirectory)/out</ArtifactsPath>
  </PropertyGroup>

</Project>
