variables:
  - name: DOTNET_NOLOGO
    value: 1
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 1
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 1
  - name: configuration
    value: release
  - name: project
    value: Webjobs.sln
