// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

namespace Microsoft.Azure.WebJobs.Host.Bindings.Path
{
    /// <summary>
    /// Represents a semantic token as generated by <see cref="BindingTemplateParser"/> during parsing of parameterized 
    /// binding template string. Then generated token may be consumed to create instance of 
    /// <see cref="BindingTemplate"/> or <see cref="BindingTemplateSource"/>.
    /// </summary>
    internal struct BindingTemplateToken
    {
        public BindingTemplateToken(string value, bool isParameter = false, int index = -1)
        {
            Value = value;
            IsParameter = isParameter;
            Index = index;
        }

        public string Value { get; private set; }

        public bool IsParameter { get; private set; }

        public int Index { get; private set; }
    }
}
