trigger:
  branches:
    include:
    - dev
    - release/*
  tags:
    include:
    - '*'

schedules:
# Run once a month to prevent disablement from inactivity.
- cron: "0 0 1 * *"
  displayName: Monthly sync
  branches:
    include:
    - dev
  always: true

resources:
  repositories:
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
  - template: ci/variables/cfs.yml@eng

extends:
  template: ci/code-mirror.yml@eng
