parameters:
- name: official
  type: boolean
  default: false
- name: skipStorage
  type: boolean
  default: false

jobs:
- job: build
  displayName: Build

  variables:
  - name: pack_dir
    value: $(Build.ArtifactStagingDirectory)/pkg

  templateContext:
    outputParentDirectory: $(Build.ArtifactStagingDirectory)
    outputs:
    - output: pipelineArtifact
      displayName: Publish logs
      path: $(pack_dir)
      artifact: drop_packages

  steps:
    - template: /eng/ci/templates/steps/install-dotnet.yml@self

    - task: DotNetCoreCLI@2
      displayName: Restore $(project)
      inputs:
        command: custom
        custom: restore
        projects: $(project)
        arguments: -v m

    - task: DotNetCoreCLI@2
      displayName: Build $(project)
      inputs:
        command: build
        projects: $(project)
        arguments: -c $(configuration) -v m --no-restore

    - task: DotNetCoreCLI@2
      displayName: Unit tests
      inputs:
        command: test
        arguments: -c $(configuration) --no-build
        projects: |
          test\Microsoft.Azure.WebJobs.Extensions.Rpc.UnitTests\*.csproj
          test\Microsoft.Azure.WebJobs.Host.UnitTests\*.csproj

    - ${{ if eq(parameters.official, true) }}:
      - template: ci/sign-files.yml@eng
        parameters:
          displayName: Sign assemblies
          folderPath: out/bin/src
          minimatch: true
          pattern: |
            **/Microsoft.Azure.WebJobs*.dll
          signType: dll-strong-name

    - task: DotNetCoreCLI@2
      displayName: Pack
      inputs:
        command: custom
        custom: pack
        arguments: -c $(configuration) -v m -o $(pack_dir) --no-build
        projects: |
          src\Microsoft.Azure.WebJobs\WebJobs.csproj
          src\Microsoft.Azure.WebJobs.Host\WebJobs.Host.csproj
          src\Microsoft.Azure.WebJobs.Host\WebJobs.Host.Sources.csproj
          src\Microsoft.Azure.WebJobs.Rpc.Core\WebJobs.Rpc.Core.csproj
          src\Microsoft.Azure.WebJobs.Extensions.Rpc\WebJobs.Extensions.Rpc.csproj
          test\Microsoft.Azure.WebJobs.Host.TestCommon\WebJobs.Host.TestCommon.csproj
          ${{ if not(parameters.skipStorage) }}:
            src\Microsoft.Azure.WebJobs.Extensions.Storage\WebJobs.Extensions.Storage.csproj

    - ${{ if eq(parameters.official, true) }}:
      - template: ci/sign-files.yml@eng
        parameters:
          displayName: Sign nuget packages
          folderPath: $(pack_dir)
          pattern: Microsoft.Azure.WebJobs*.nupkg
          signType: nuget
