# Only to be used for internal builds.

jobs:
- job: RunIntegrationTests
  displayName: Run Integration Tests

  steps:
  - template: /eng/ci/templates/steps/install-dotnet.yml@self

  - task: AzureKeyVault@1
    inputs:
      # Note: This is actually a Service Connection in DevOps, not an Azure subscription name
      azureSubscription: Azure-Functions-Host-CI-internal
      keyVaultName: azure-webjobs-sdk-ci
      secretsFilter: '*'

  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: test
      arguments: -c $(configuration)
      projects: |
        test\Microsoft.Azure.WebJobs.Host.FunctionalTests\*.csproj
        test\Microsoft.Azure.WebJobs.Logging.FunctionalTests\*.csproj
        test\Microsoft.Azure.WebJobs.Host.EndToEndTests\*.csproj
    env:
      AzureWebJobsDashboard: $(Storage)
      AzureWebJobsStorage: $(Storage)
      AzureWebJobsSecondaryStorage: $(Storage2)
      AzureWebJobsServiceBus: $(ServiceBus)
      AzureWebJobsServiceBusSecondary: $(ServiceBus2)
      AzureWebJobsTestHubConnection: $(EventHub)
      AzureWebJobsTestHubConnection2: $(EventHub2)
      APPINSIGHTS_REPORTER_KEY: $(AppInsights)
      ConnectionStrings:ServiceBus: $(ServiceBus)
      ConnectionStrings:ServiceBusSecondary: $(ServiceBus2)