<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>$(HostStorageVersion)</Version>
    <InformationalVersion>$(Version) Commit hash: $(CommitHash)</InformationalVersion>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <PackageId>Microsoft.Azure.WebJobs.Host.Storage</PackageId>
    <Description>This package contains Azure Storage based implementations of some WebJobs SDK component interfaces. For more information, please visit https://go.microsoft.com/fwlink/?linkid=2279708.</Description>
    <AssemblyName>Microsoft.Azure.WebJobs.Host.Storage</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.22.1" />
    <PackageReference Include="System.Text.Json" Version="6.0.11" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.7.5" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta004" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.Azure.WebJobs.Host\WebJobs.Host.csproj" />
  </ItemGroup>

</Project>
