<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <InformationalVersion>$(Version) Commit hash: $(CommitHash)</InformationalVersion>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageId>Microsoft.Azure.WebJobs.Logging</PackageId>
    <Description>This package provides logging related Types and capabilities to the WebJobs SDK. For more information, please visit https://go.microsoft.com/fwlink/?linkid=2279708.</Description>
    <AssemblyName>Microsoft.Azure.WebJobs.Logging</AssemblyName>
    <RootNamespace>Microsoft.Azure.WebJobs.Logging</RootNamespace>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Cosmos.Table" Version="1.0.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta004" PrivateAssets="all" />
  </ItemGroup>

</Project>